pipeline {
	agent any 
	stages {
		stage('Build') {
			steps{
				sh 'mvn -f JenkinsPractice/JavaTomcat/pom.xml clean package'

			}
			post {
				success {
					echo "Archive Artifacts" 
					archiveArtifacts artifacts: '**/*.war'
					
				}
			}
		}
		stage('Create Tomcat Image') {
			steps {
				copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
				echo "Building Docker Image .."
				sh '''
				original_pwd=$(pwd -P)
				cd JenkinsPractice/JavaTomcat
				docker build -t localtomcatimg:$BUILD_NUMBER .
				cd $original_pwd
				sh '''
			}
		}
              stage('Deploy to Staging') {
			steps {
				echo "Running in Staging Environment..."
				sh '''
				docker run -itd --name tomcatstagingenv -p 8085:8080 localtomcatimg:$BUILD_NUMBER
				sh '''
 
			}
		}
	}	
	
}
