---
- name: Setup webserver
  hosts: web
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2
      service:
        name: apache2
        state: started
        enabled: true 
