version: "3.3"
services:
  web:
    build: .
    ports:
      - "3000:8003"
    networks:
      - testnetwork
    volumes:
      - testvolume:/var/node
    environment:
         ENV: development
networks:
  testnetwork:
volumes:
  testvolume:
